# .checkov.yaml - Example configuration to suppress a policy for a specific file

# checkov:skip=CKV2_GHA_1:This script must write to gh-pages

#checkov:skip=CKV2_GHA_1:The bucket is a public static content host

skip-check:
  policy_id: CKV2_GHA_1  # Example Checkov policy ID to suppress
  file_path: .github/workflows/create_website.yaml
  suppress_comment: "This script must write to gh-pages"

skip-path: 
  file_path: .github/workflows/create_website.yaml
  suppress_comment: "This script must write to gh-pages"