site_name: Intermediate bash/Linux
repo_url: https://github.com/UPPMAX/naiss_intermediate_bash_linux
edit_uri: blob/main/docs/

site_description: Material for the course Intermediate bash/Linux
site_dir: site.build

theme:
  name: readthedocs
  locale: en
  logo:
    images/bash-script.png
    #  static_templates:
    #- sitemap.html
  include_sidebar: true
  include_homepage_in_sidebar: true
  font:
    code: Robot Mono
  features:
    - toc.follow
    - toc.integrate
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view
  tabs: true
  language: en

nav:
  - Common:
      - Home: index.md
      - Learning outcomes: learning_outcomes.md
      - Course dates: course_dates.md
      - Schedule: schedule.md
      - Prerequisites: prerequisites.md
      - Evaluation: evaluation.md
  - Lessons Day 1 (smarter command line):
      - Introduction: sessions/intro.md
      - Linux pipe: sessions/pipe.md
      - Linux tools (wc, cut): sessions/wc_cut.md
      - Searching using regular expressions and grep: sessions/regular_expressions_and_grep/README.md
      - Using the programming language AWK: sessions/awk/README.md
  - Lessons Day 2 (smarter bash):
      - Scripting: sessions/scripting/README.md
      - Redirects: sessions/redirects.md
      - Environment variables: sessions/env_vars.md
      - Symbolic links: sessions/symlinks.md
      - Archiving/compressing data: sessions/arch.md
      - Linux tools (sed): sessions/sed.md
      - Quality of life: sessions/qual.md
  - Other teaching materials:
      - Books: books/README.md
      - Courses: courses.md
      - Videos: videos.md
  - Miscellaneous:
      - Lesson plans: lesson_plans/README.md
      - Evaluations: evaluations/README.md
      - Reflections: reflections/README.md

not_in_nav: |
  lesson_plans/20250602/README.md
  lesson_plans/20250603/README.md
  meeting_notes/README.md
  meeting_notes/20250403.md
  meeting_notes/20250409.md
  misc/test_admonitions.md
  misc/test_mermaid.md

plugins:
  - search
  - external-markdown
  - mkdocstrings
  - markdown-exec
  - open-in-new-tab

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details # Makes admonitions collapsible, from https://mkdocs-material-rtd-test.readthedocs.io/en/latest/reference/admonitions/#details
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - smarty
  - pymdownx.details
  - pymdownx.superfences
  - codehilite
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
      separator: "__"
  - admonition
  - pymdownx.details
