site_name: Intermediate bash/Linux 
repo_url: https://github.com/UPPMAX/naiss_intermediate_bash_linux
edit_uri: blob/main/docs/

site_description: Material for the course Intermediate bash/Linux
site_dir: site.build

theme:
  name: readthedocs
  locale: en
  logo: images/bash-script.png
    #  static_templates:
    #- sitemap.html
  include_sidebar: true
  include_homepage_in_sidebar: true
  font:
    code: Robot Mono
  features:
    - toc.follow
    - toc.integrate
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view
  tabs: true
  language: en

extra_css:
  - css/extra.css
    #extra_javascript:
    #  - js/popper.min.js
    #  - js/tippy-bundle.umd.js
    #  - js/clipboard.js

nav:
  - Common:
    - Home: index.md
    - Learning outcomes: learning_outcomes.md
    - Course dates: course_dates.md
    - Schedule: schedule.md
    - Prerequisites: prerequisites.md
  - Lessons Day 1 (smarter command line): 
    - Introduction: sessions/intro.md
    - Linux pipe: sessions/pipe.md
    - Linux tools (wc, cut): sessions/wc_cut.md
    - Regular expressions and grep: sessions/regular_expressions_and_grep/README.md
    - Linux tools (awk): sessions/awk.md
  - Lessons Day 2 (smarter bash): 
    - Scripting: sessions/scripting.md
    - Redirects: sessions/redirects.md
    - Environment variables: sessions/env_vars.md
    - Symbolic links: sessions/symlinks.md
    - Archiving/compressing data: sessions/arch.md
    - Linux tools (sed): sessions/sed.md  
    - Quality of life: sessions/qual.md
    - Summary: summary.md
  - Extras: 
    - More scripting: more_script.md
    - Books: books/README.md

plugins:
  - search
  - external-markdown
  - mkdocstrings
  - markdown-exec
  - open-in-new-tab

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details # Makes admonitions collapsible, from https://mkdocs-material-rtd-test.readthedocs.io/en/latest/reference/admonitions/#details
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - smarty
  - pymdownx.details
  - pymdownx.superfences
  - codehilite
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
      separator: "__"
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        # Mermaid diagrams, from https://facelessuser.github.io/pymdown-extensions/extras/mermaid/#using-in-mkdocs
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  

# For mermaid, from https://facelessuser.github.io/pymdown-extensions/extras/mermaid/#using-in-mkdocs
extra_javascript:
  # - optionalConfig.js
  - https://cdn.jsdelivr.net/npm/mermaid@11.5.0/dist/mermaid.min.js # For mermaid
  - extra-loader-B5CKpNQx.js # For mermaid, from https://github.com/facelessuser/pymdown-extensions/blob/main/docs/theme/assets/pymdownx-extras/extra-loader-B5CKpNQx.js
